- name : configuring frontend
  hosts: frontend
  become: yes
  tasks:
  - name : enabling nginx
    ansible.builtin.command: dnf module enable nodejs:1.24 -y 
    
  - name : installing nginx
    ansible.builtin.package:
      name: nodejs
      state: present

  - name : remove entire html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: creating html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name : download the code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unarchieve frontend
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes
  
  - name: remove default nginx
    ansible.builtin.file:
      state: absent
      path: /etc/nginx/nginx.conf

  - name: copy nginx.conf
    ansible.builtin.template:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: resatrt nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes
  