- name: configure user module
  hosts: user
  become: yes
  tasks: 
  - name: enabling nodejs module
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: creating system user 
    ansible.builtin.user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      comment: roboshop user
      system: yes
    
  - name: creating app folder
    ansible.builtin.file:
      path: /app
      state: directory

  - name: 